version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hoge
      POSTGRES_DB: hoge
    tty: true
    restart: always
    user: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro