version: '3'
services:
  server:
    container_name: user-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-compose-sample.env
    ports:
      - 8000:8000
    tty: true
    volumes:
      - .:/go/src/User-API
    depends_on:
      - postgres
    command: go run main.go

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hoge
      POSTGRES_DB: hoge
    tty: true
    restart: always
    user: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro