version: '3'
services:
  server:
    container_name: user-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-compose-sample.env
    ports:
      - 8000:8000
    tty: true
    volumes:
      - .:/go/src/User-API
    depends_on:
      - db
    command: go run main.go

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=hoge
      - POSTGRES_PASSWORD=hoge
    tty: true
    restart: always
    user: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro