version: '3'
services:
  server:
    container_name: server-user-api
    build:
      context: .
      dockerfile: .Dockerfile
    env_file:
      - docker-compose-sample.env
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./User-API:/go/src/github.com/seipan/User-API
    depends_on:
      - db
    command: go run main.go

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    tty: true
    restart: always
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/testdb?sslmode=disable
    links: 
      - postgres:postgres
    restart: always
    depends_on:
      - postgres