version: '3'
services:
  server:
    container_name: server-user-api
    build:
      context: .
      dockerfile: .Dockerfile
    env_file:
      - docker-compose-sample.env
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./User-API:/go/src/github.com/seipan/User-API
    depends_on:
      - db
    command: go run main.go

  db:
    container_name: db-user-api
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - docker-compose-sample.env
    restart: always